/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function ArticlesBlog() {
  return (
    <div className="box-border flex relative flex-col shrink-0 gap-0 justify-between mr-0 mb-24 bg-white bg-center bg-no-repeat bg-cover rounded max-md:mb-24">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
          <div className="box-border flex relative flex-col shrink-0 pt-px mt-0 mb-2 bg-black bg-opacity-50 size-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                <div className="box-border flex relative flex-col shrink-0 pt-8 pr-8 pb-16 pl-8 mt-5 w-auto max-w-full text-white bg-sky-950 bg-opacity-0">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                      <div className="box-border flex relative flex-col shrink-0 mt-auto max-md:mt-auto max-sm:mx-auto">
                        <div className="flex gap-5 max-sm:flex-col max-sm:gap-0">
                          <div className="flex flex-col w-6/12 max-sm:ml-0 max-sm:w-full">
                            <div className="box-border relative shrink-0 mt-auto mr-auto h-auto text-4xl leading-10 text-white max-w-[94%] max-md:mt-auto">
                              Insight&nbsp;
                            </div>
                          </div>
                          <div className="flex flex-col ml-5 w-6/12 max-sm:ml-0 max-sm:w-full">
                            <button
                              className="box-border relative shrink-0 px-6 py-4 mt-5 ml-auto text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white] max-md:mb-auto"
                              // openLinkInNewTab={false}
                            >
                              View More Articles!
                            </button>
                          </div>
                        </div>
                      </div>
                      <div className="box-border flex relative flex-col items-center shrink-0 px-5 py-2.5 mt-5 rounded border-0 border-solid bg-black bg-opacity-50 border-[black] max-md:pr-5 max-md:pb-5">
                        <div className="flex gap-5 max-md:flex-col max-md:gap-0 max-lg:flex-wrap">
                          <div className="flex flex-col items-center justify-center w-[33%] max-md:ml-0 max-md:w-full max-lg:w-full">
                            <div className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 bg-white rounded-lg border border-black border-solid shadow-sm">
                              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                <div className="flex flex-col items-center w-full max-md:ml-0 max-md:w-full">
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc2f5550b71904a0cacf85e7518915f06"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[1.56] min-h-[20px] min-w-[20px] rounded-[50px]"
                                  />
                                  <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-center w-[85%]">
                                    <blockquote className="p-0 my-0 mr-0 ml-10 border-[none]">
                                      <p
                                        // class="p1"
                                        className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                                      >
                                        <span className="mx-auto text-base leading-6 text-[#000000]">
                                          {/* <font
                                            face="Manrope, sans-serif"
                                            color="#000000"
                                          > */}
                                            <span className="mx-auto text-2xl text-center">
                                              Laundry Tips
                                            </span>
                                          {/* </font> */}
                                        </span>
                                      </p>
                                    </blockquote>
                                  </div>
                                  <div className="box-border relative shrink-0 p-1.5 mx-auto mt-5 h-auto text-base leading-6 rounded-md shadow-xl border-neutral-600">
                                    <span className="text-black"> 
                                    {/* style='color: rgb(0, 0, 0); font-family: "Helvetica Neue"; font-size: 13px;'> */}
                                      Vestibulum pede vivamus natoque egestas
                                      risus integer mi euismod sodales amet.
                                      Conubia natoque dis rutrum cras ultricies
                                      facilisi sodales justo molestie
                                      scelerisque ligula.
                                    </span>
                                  </div>
                                  <div className="box-border flex relative flex-col shrink-0 mt-5">
                                    <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                      <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                        <button
                                          className="box-border relative shrink-0 px-6 py-4 mx-auto mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                                          // openLinkInNewTab={false}
                                        >
                                          Read More
                                        </button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                            <div className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 bg-white rounded-lg border border-black border-solid shadow-sm">
                              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fe902c289830247b9bfc2ef549de5fe4e"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[1.55] min-h-[20px] min-w-[20px] rounded-[50px]"
                                  />
                                  <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-center w-[85%]">
                                    <blockquote className="p-0 my-0 mr-0 ml-10 border-[none]">
                                      <p
                                        // class="p1"
                                        className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                                      >
                                        <span className="mx-auto text-base leading-6 text-[#000000]">
                                          {/* <font
                                            face="Manrope, sans-serif"
                                            color="#000000"
                                          > */}
                                            <span className="mx-auto text-2xl text-center">
                                              Treatment Tips
                                            </span>
                                          {/* </font> */}
                                        </span>
                                      </p>
                                    </blockquote>
                                  </div>
                                  <div className="box-border relative shrink-0 p-1.5 mx-auto mt-5 h-auto text-base leading-6 rounded-md shadow-xl border-neutral-600">
                                    <span className="text-black">
                                       {/* style='color: rgb(0, 0, 0); font-family: "Helvetica Neue"; font-size: 13px;'> */}
                                      Vestibulum pede vivamus natoque egestas
                                      risus integer mi euismod sodales amet.
                                      Conubia natoque dis rutrum cras ultricies
                                      facilisi sodales justo molestie
                                      scelerisque ligula.
                                    </span>
                                  </div>
                                  <div className="box-border flex relative flex-col shrink-0 mt-5">
                                    <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                      <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                        <button
                                          className="box-border relative shrink-0 px-6 py-4 mx-auto mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                                          // openLinkInNewTab={false}
                                        >
                                          Read More
                                        </button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                            <div className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 bg-white rounded-lg border border-black border-solid shadow-sm max-md:pb-2.5">
                              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F27a3a40bc046498eb8e4bc761122c81e"
                                    className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[1.56] min-h-[20px] min-w-[20px] rounded-[50px]"
                                  />
                                  <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-center w-[85%]">
                                    <blockquote className="p-0 my-0 mr-0 ml-10 border-[none]">
                                      <p
                                        // class="p1"
                                        className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                                      >
                                        <span className="mx-auto text-base leading-6 text-[#000000]">
                                          {/* <font
                                            face="Manrope, sans-serif"
                                            color="#000000"
                                          > */}
                                            <span className="mx-auto w-full text-2xl text-center">
                                              Delivery Tips
                                            </span>
                                          {/* </font> */}
                                        </span>
                                      </p>
                                    </blockquote>
                                  </div>
                                  <div className="box-border relative shrink-0 p-1.5 mx-auto mt-5 h-auto text-base leading-6 rounded-md shadow-xl border-neutral-600">
                                    <span className="text-black">
                                       {/* style='color: rgb(0, 0, 0); font-family: "Helvetica Neue"; font-size: 13px;'> */}
                                      Vestibulum pede vivamus natoque egestas
                                      risus integer mi euismod sodales amet.
                                      Conubia natoque dis rutrum cras ultricies
                                      facilisi sodales justo molestie
                                      scelerisque ligula.
                                    </span>
                                  </div>
                                  <div className="box-border flex relative flex-col shrink-0 mt-5">
                                    <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                      <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                        <button
                                          className="box-border relative shrink-0 px-6 py-4 mx-auto mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                                          // openLinkInNewTab={false}
                                        >
                                          Read More
                                        </button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
