/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function CallToAction() {
  return (
    <div className="box-border flex relative flex-col shrink-0 gap-0 justify-between p-5 mt-px mr-0 mb-24 bg-white bg-center bg-no-repeat bg-cover rounded bg-[url(https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F1564e10fd3114891b49510fda87c6e9d?format=webp)]">
      <div className="flex gap-5 max-lg:flex-col max-md:gap-0">
        <div className="flex flex-col  w-6/12 max-md:ml-0 max-lg:w-full">
          <div className="box-border flex relative flex-col shrink-0 pt-8 pr-8 pb-16 pl-16 mt-5 w-auto min-h-[394px] max-h-[500px] max-w-full text-white bg-sky-950 bg-opacity-50">
            <div className="flex gap-5 max-lg:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-lg:w-full">
                <div className="box-border relative shrink-0 mt-5 h-auto text-base leading-6 text-white">
                  Our Service
                </div>
                <div className="box-border relative shrink-0 mt-5 w-full h-auto text-4xl leading-10 text-white max-w-[94%]">
                  Ready to get Laundry Service?
                </div>
                <div className="box-border relative shrink-0 mt-5 h-auto text-base text-white">
                  <p
                    // class="p1"
                    className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                  >
                    <span className="text-base leading-6">
                      {/* <font face="Manrope, sans-serif"> */}
                        Arcu eget malesuada imperdiet ornare pretium fringilla
                        elit
                      {/* </font> */}
                      {/* <font face="Manrope, sans-serif"> </font> */}
                      {/* <font face="Manrope, sans-serif"> */}
                        nullam. Orci elementum nec netus placerat convallis
                        cursus class diam arcu tincidunt sed. Dolor tristique
                        parturient consequat suscipit malesuada viverra proin
                        commodo.
                      {/* </font> */}
                    </span>
                  </p>
                </div>
                <button
                  className="box-border relative shrink-0 px-6 py-4 mt-5 mr-auto text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                  // openLinkInNewTab={false}
                >
                  Discover More
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col w-6/12 max-md:ml-0 max-lg:w-full">
          <div className="box-border flex relative flex-col shrink-0 px-5 pb-4 mt-5 bg-white rounded border-solid border-[3px] border-[black]">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                <div className="box-border flex relative flex-col shrink-0 px-2.5 mt-5">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                      <label
                        text="<p>Name</p>"
                        htmlFor="name"
                        className="box-border flex relative flex-col shrink-0 mt-5 leading-6"
                      />
                      <input
                        type="text"
                        placeholder="Name"
                        name="name"
                        className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 rounded border border-solid border-stone-300"
                        required
                      />
                    </div>
                    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                      <label
                        text="<p>Phone</p>"
                        htmlFor="phone"
                        className="box-border flex relative flex-col shrink-0 mt-5 leading-6"
                      />
                      <input
                        type="text"
                        placeholder="Phone"
                        name="phone"
                        className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 rounded border border-solid border-stone-300"
                        required
                      />
                    </div>
                  </div>
                </div>
                <div className="box-border flex relative flex-col shrink-0 px-2.5 -mt-1">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                      <label
                        text="<p>Email</p>"
                        htmlFor="email"
                        className="box-border flex relative flex-col shrink-0 mt-5 leading-6"
                      />
                      <input
                        type="text"
                        placeholder="Email"
                        name="email"
                        className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 rounded border border-solid border-stone-300"
                        required
                      />
                    </div>
                    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                      <label
                        text="<p>Date</p>"
                        htmlFor="date"
                        className="box-border flex relative flex-col shrink-0 mt-5 leading-6"
                      />
                      <input
                        type="text"
                        placeholder="Date"
                        name="date"
                        className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 rounded border border-solid border-stone-300"
                        required
                      />
                    </div>
                  </div>
                </div>
                <div className="box-border flex relative flex-col shrink-0 px-2.5 -mt-1">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                      <label
                        text="<p>Message</p>"
                        htmlFor="message"
                        className="box-border flex relative flex-col shrink-0 mt-5 leading-6"
                      />
                      <textarea
                        placeholder="Message"
                        name="message"
                        className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 rounded border border-solid border-stone-300"
                        required={false}
                      />
                    </div>
                    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                      <label
                        text="<p>Pickup Time</p>"
                        htmlFor="pickup_time"
                        className="box-border flex relative flex-col shrink-0 mt-5 leading-6"
                      />
                      <input
                        type="text"
                        placeholder="Pickup Time"
                        name="pickup_time"
                        className="box-border flex relative flex-col shrink-0 p-2.5 mt-5 rounded border border-solid border-stone-300"
                        required={false}
                      />
                    </div>
                  </div>
                </div>
                <button
                  className="box-border relative shrink-0 px-6 py-4 mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                  // openLinkInNewTab={false}
                >
                  Pickup Now
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
