/**
 * This code was generated by Builder.io.
 */
'use client'
import Link from "next/link";
import * as React from "react";
import { authUserEmail } from "../server actions/server actions";
import { closeSession } from "../server actions/server actions";
import { useState, useEffect } from "react";
import { signOut, getAuth } from "firebase/auth";
import { auth } from "../firebase/firebaseConfig";
import { useRouter } from "next/navigation";
import { FaSpinner } from "react-icons/fa";
import { useTransition } from "react";

export default function LaundryHeader() {

  const [isauth, setAuth] = useState(null)
  const [isPending, startTransition] = useTransition()
  const [isLoadingLogout, setIsLoadingLogout] = useState(false)
  const [isLoadingSignUp, setIsLoadingSignUp] = useState(false)
 
  const router = useRouter()

  useEffect(()=>{
    const getActiveAuth = async() => {
      const activeauth = await authUserEmail()
      setAuth(activeauth)
      
      // 
    }
    getActiveAuth()
  },[isauth, auth])


  const clearAuth = async() =>{
    startTransition(async()=>{
      setIsLoadingLogout(true)
    let timerId
    try{
      await signOut(auth); 
      timerId = setTimeout(()=>{setIsLoadingLogout(false);},7000)
    }
    catch(err){
      console.log(err)
    }
    finally{
      timerId =setTimeout(()=>setIsLoadingLogout(false), 7000)
      clearTimeout(timerId)
      
    }
    })
    
  }

  return (
    <div
      className="w-full h-full box-border flex sticky top-0 z-20 flex-col shrink-0 px-5 bg-white border-black border-solid min-h-[50px]"
      // maxWidth={1200}
      // lazyLoad={false}
    >
      <section className="sticky top-0 z-20 box-border flex-col grow shrink-0 self-stretch px-5 pb-2 mx-auto w-full bg-white border-black border-solid max-w-[1400px] min-h-[50px]">
        <div className="box-border flex relative flex-col shrink-0 mt-2 mr-auto w-full">
          <div className="flex gap-5 sticky top-0 z-20 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Ffe4e5f3cc6494e3f9d1c3dd18cc1fded"
                className="box-border object-cover overflow-hidden shrink-0 mt-0 mb-auto aspect-square h-[70px] min-h-[20px] min-w-[20px] w-[70px] max-md:w-16 max-md:h-16"
              />
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
              <div className="box-border flex relative flex-col shrink-0 pr-2.5 mr-auto -ml-16 w-[500px] max-w-[700px] max-md:hidden max-sm:hidden">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
                    <a
                      //onClick={()=>{window.location.href='/'}}
                      href="/"
                      className="box-border relative shrink-0 mx-auto mt-5 h-auto cursor-pointer pointer-events-auto"
                    >
                      Home
                    </a>
                  </div>
                  <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                    <a
                      href="/services"
                      className="box-border relative shrink-0 mx-auto mt-5 h-auto cursor-pointer pointer-events-auto"
                    >
                      Services
                    </a>
                  </div>
                  <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                    <a
                      href="/about"
                      className="box-border relative shrink-0 mx-auto mt-5 w-20 h-auto cursor-pointer pointer-events-auto"
                    >
                      About Us
                    </a>
                  </div>
                  <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                    <a
                      href="/whychooseus"
                      className="box-border relative shrink-0 mx-auto mt-5 h-auto cursor-pointer pointer-events-auto"
                    >
                      WhyChooseUs
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
              <div className="box-border flex relative flex-col shrink-0 px-2.5 -mt-9 mr-auto mb-auto ml-40 max-w-[279px] w-[300px] max-lg:hidden max-sm:hidden">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                    <div className="box-border flex relative flex-col shrink-0 mt-5">
                      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                        <div className="flex flex-col w-[110px] max-md:ml-0 max-md:w-full">
                          <Link
                            href={'/signup'}
                            className="box-border relative shrink-0 px-6 py-4 mt-5 text-center border border-[#1665F8] rounded appearance-none cursor-pointer bg-[white] text-[#1665F8] hover:bg-[#1665F8] transition-all hover:text-white "
                            // openLinkInNewTab={false}
                            disabled={isLoadingSignUp}
                          >
                            {isLoadingSignUp? <FaSpinner className="animate-spin mx-auto"/> : 'Sign Up'}
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                    <div className="box-border flex relative flex-col shrink-0 mt-5">
                      <div className="flex gap-5 max-md:flex-col max-md:gap-0">

                        
                        {isauth && auth ? 
                          <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                            <Link
                            onClick={async()=>{ await clearAuth(); await closeSession(); window.location.href='/login'}}
                            href={'/login'}
                            disabled={isPending}
                              className="box-border relative shrink-0 px-6 py-4 mt-5 text-center rounded border border-[#1665F8] appearance-none cursor-pointer text-[white] bg-[#1665F8] hover:text-[#1665F8] transition-all hover:bg-white "
                              // openLinkInNewTab={false}
                            >
                              {isPending? <FaSpinner className="animate-spin mx-auto"/> : 'Logout'}
                              
                            </Link>
                          </div> :
                          <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                            <a
                            href={'/login'}
                              className="box-border relative shrink-0 px-6 py-4 mt-5 text-center rounded border border-[#1665F8] appearance-none cursor-pointer text-[white] bg-[#1665F8] hover:text-[#1665F8] transition-all hover:bg-white "
                              // openLinkInNewTab={false}
                            >
                              Login
                            </a>  
                        </div>}

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full ">
              <div className="box-border flex relative flex-col shrink-0 px-2.5 -mt-9 mr-auto mb-auto ml-28 w-full max-w-[273px]">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0" />
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fc55a5ccdcf7e4373a29a84e42a4eb224"
                className="box-border object-cover overflow-hidden shrink-0 mb-auto ml-auto w-full aspect-[0.99] max-w-[32px] min-h-[20px] min-w-[20px] hidden max-lg:flex md:max-2xl:mt-8 max-md:mb-auto max-sm:flex xsm:max-md:-mt-8"
              />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
