/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Support() {
  return (
    <div className="box-border flex relative flex-col shrink-0 px-10 pb-10 mt-6 bg-white shadow-sm">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0 max-lg:flex-wrap">
        <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full max-lg:w-[100%]">
          <div className="box-border flex relative flex-col shrink-0 px-5 pb-8 mt-5 rounded-xl border border-solid shadow-sm border-[black]">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F8dae455d96ea492d944643411bec24e5"
                  className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-square max-w-[64px] min-h-[20px] min-w-[20px]"
                />
                <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-3xl leading-6">
                  Use Eco
                </div>
                <div className="box-border relative shrink-0 px-2.5 mx-auto mt-5 h-auto text-base leading-6">
                  <span>
                  {/* style='font-family: "Helvetica Neue"; font-size: 13px;'> */}
                    Montes dictum faucibus rutrum morbi sagittis blandit iaculis
                    posuere neque nunc ac tortor
                  </span>
                  <font face="Manrope, sans-serif">
                    <span className="mx-auto">...</span>
                  </font>
                </div>
                <button
                  className="box-border relative shrink-0 px-6 py-4 mx-auto mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                  // openLinkInNewTab={false}
                >
                  Learn More
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
          <div className="box-border flex relative flex-col shrink-0 px-5 pb-8 mt-5 rounded-xl border border-solid shadow-sm border-[black]">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5a86dc22aae8407ba17350a7bc7f800b"
                  className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-square max-w-[64px] min-h-[20px] min-w-[20px]"
                />
                <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-3xl leading-6">
                  Fast Service
                </div>
                <div className="box-border relative shrink-0 px-2.5 mx-auto mt-5 h-auto text-base leading-6">
                  <span>
                  {/* style='font-family: "Helvetica Neue"; font-size: 13px;'> */}
                    Montes dictum faucibus rutrum morbi sagittis blandit iaculis
                    posuere neque nunc ac tortor
                  </span>
                  <font face="Manrope, sans-serif">
                    <span className="mx-auto">...</span>
                  </font>
                </div>
                <button
                  className="box-border relative shrink-0 px-6 py-4 mx-auto mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                  // openLinkInNewTab={false}
                >
                  Learn More
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
          <div className="box-border flex relative flex-col shrink-0 px-5 pb-8 mt-5 rounded-xl border border-solid shadow-sm border-[black]">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F21497f4a2b564617a8eba6a6778175bf"
                  className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-square max-w-[64px] min-h-[20px] min-w-[20px]"
                />
                <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-3xl leading-6">
                  24/7 Support
                </div>
                <div className="box-border relative shrink-0 px-2.5 mx-auto mt-5 h-auto text-base leading-6">
                  <span>
                  {/* style='font-family: "Helvetica Neue"; font-size: 13px;'> */}
                    Montes dictum faucibus rutrum morbi sagittis blandit iaculis
                    posuere neque nunc ac tortor
                  </span>
                  <font face="Manrope, sans-serif">
                    <span className="mx-auto">...</span>
                  </font>
                </div>
                <button
                  className="box-border relative shrink-0 px-6 py-4 mx-auto mt-5 text-center bg-blue-600 rounded appearance-none cursor-pointer text-[white]"
                  // openLinkInNewTab={false}
                >
                  Learn More
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
