/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function Testimonials() {
  return (
    <div className="max-xsm:pr-10 xsm:max-2xl:pr-0 box-border flex relative flex-col shrink-0 gap-0 justify-between mr-0 mb-24 bg-white bg-center bg-no-repeat bg-cover rounded bg-[url(https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F5ea1089a8cd44b328caf928701bab449)]">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
          <div className="box-border flex relative flex-col shrink-0 pt-px mt-0 mb-2 bg-black bg-opacity-50 size-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                <div className="box-border flex relative flex-col shrink-0 pt-8 pr-8 pb-16 pl-8 mt-5 w-auto max-w-full text-white bg-sky-950 bg-opacity-0">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                      <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-base leading-6 text-white">
                        Our Testimonial
                      </div>
                      <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-4xl leading-10 text-white max-w-[94%]">
                        What they Say
                      </div>
                      <div className="box-border relative shrink-0 mt-5 h-auto text-base text-white">
                        <p
                          // class="p1"
                          className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                        >
                          <span className="text-base leading-6">
                            {/* <font face="Manrope, sans-serif"> */}
                              Arcu eget malesuada imperdiet ornare pretium
                              fringilla elit
                            {/* </font> */}
                            {/* <font face="Manrope, sans-serif"> </font> */}
                            {/* <font face="Manrope, sans-serif"> */}
                              nullam. Orci elementum nec netus placerat
                              convallis cursus class diam arcu tincidunt sed.
                              Dolor tristique parturient consequat suscipit
                              malesuada viverra proin commodo.
                            {/* </font> */}
                          </span>
                        </p>
                      </div>
                      <div className="box-border flex relative flex-col shrink-0 px-5 py-2.5 mt-5 rounded border-4 border-solid bg-black bg-opacity-50 border-[black]">
                        <div className="flex gap-5 max-md:flex-col max-md:gap-0 max-lg:flex-wrap">
                          <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full max-lg:w-full">
                            <div className="box-border flex relative flex-col shrink-0 px-2.5 pt-2.5 pb-8 mt-6 bg-white rounded-lg border border-black border-solid shadow-sm">
                              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                    className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                  />
                                  <div className="box-border relative shrink-0 mt-5 h-auto">
                                    <blockquote className="p-0 my-0 mr-0 ml-10 border-[none]">
                                      <p
                                        // class="p1"
                                        className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                                      >
                                        <span className="mx-auto text-base leading-6 text-[#000000]">
                                          {/* <font
                                            face="Manrope, sans-serif"
                                            color="#000000"
                                          > */}
                                            <span className="mx-auto text-center text-[#000000]">
                                              Montes dictum faucibus rutrum
                                              morbi sagittis blandit iaculis
                                              posuere neque nunc ac tortor
                                            </span>
                                          {/* </font> */}
                                        </span>
                                      </p>
                                    </blockquote>
                                  </div>
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F954ca1b65f8e4bf08d3de07289bca995"
                                    className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-square max-w-[100px] min-h-[20px] min-w-[20px] rounded-[50px]"
                                  />
                                  <div className="box-border relative shrink-0 mx-auto mt-5 h-auto text-[#000000]">
                                    {/* <font color="#000000"> */}
                                      {/* <font face="Manrope, sans-serif"> */}
                                        <span className="mx-auto leading-6 text-[#000000]">
                                          Lilian Bell
                                        </span>
                                      {/* </font> */}
                                    {/* </font> */}
                                  </div>
                                  <div className="box-border flex relative flex-row shrink-0 mx-auto mt-5 max-w-[250px]">
                                    <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5">
                                      <div className="flex gap-1">
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                            <div className="box-border flex relative flex-col shrink-0 px-2.5 pt-2.5 pb-8 mt-5 bg-white rounded-lg border border-black border-solid shadow-sm">
                              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                    className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                  />
                                  <div className="box-border relative shrink-0 mt-5 h-auto text-left">
                                    <blockquote className="p-0 my-0 mr-0 ml-10 border-[none]">
                                      <p
                                        // class="p1"
                                        className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                                      >
                                        <span className="mx-auto text-base leading-6 text-[#000000]">
                                          {/* <font
                                            face="Manrope, sans-serif"
                                            color="#000000"
                                          > */}
                                            <span className="mx-auto text-center text-[#000000]">
                                              Montes dictum faucibus rutrum
                                              morbi sagittis blandit iaculis
                                              posuere neque nunc ac tortor
                                            </span>
                                          {/* </font> */}
                                        </span>
                                      </p>
                                    </blockquote>
                                  </div>
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F274d7abe7e384da9a884e4714fcdf82a"
                                    className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-square max-w-[100px] min-h-[20px] min-w-[20px] rounded-[50px]"
                                  />
                                  <div className="box-border relative shrink-0 mx-auto mt-5 h-auto">
                                    {/* <font color="#000000"> */}
                                      <span className="mx-auto leading-6 text-[#000000]">
                                        {/* <font face="Manrope, sans-serif"> */}
                                          Vivian Ashley
                                        {/* </font> */}
                                      </span>
                                    {/* </font> */}
                                  </div>
                                  <div className="box-border flex relative flex-row shrink-0 mx-auto mt-5 max-w-[250px]">
                                    <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5">
                                      <div className="flex gap-1">
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                            <div className="box-border flex relative flex-col shrink-0 px-2.5 pt-2.5 pb-8 mt-5 bg-white rounded-lg border border-black border-solid shadow-sm">
                              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                                <div className="flex flex-col w-full max-md:ml-0 max-md:w-full">
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                    className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                  />
                                  <div className="box-border relative shrink-0 mt-5 h-auto">
                                    <blockquote className="p-0 my-0 mr-0 ml-10 border-[none]">
                                      <p
                                        // class="p1"
                                        className="text-sm normal-nums  leading-[normal] text-start tracking-[normal]"
                                      >
                                        <span className="mx-auto text-base leading-6">
                                          {/* <font
                                            face="Manrope, sans-serif"
                                            color="#000000"
                                          > */}
                                            <span className="mx-auto text-center text-[#000000]">
                                              Montes dictum faucibus rutrum
                                              morbi sagittis blandit iaculis
                                              posuere neque nunc ac tortor
                                            </span>
                                          {/* </font> */}
                                        </span>
                                      </p>
                                    </blockquote>
                                  </div>
                                  <img
                                    loading="lazy"
                                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2Fd2f34cd613024733a15d1d5e82f1953b"
                                    className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-square max-w-[100px] min-h-[20px] min-w-[20px] rounded-[50px]"
                                  />
                                  <div className="box-border relative shrink-0 mx-auto mt-5 h-auto leading-6 text-black max-md:mx-auto max-sm:mx-auto">
                                    Todd Scott
                                  </div>
                                  <div className="box-border flex relative flex-row shrink-0 mx-auto mt-5 max-w-[250px]">
                                    <div className="box-border flex relative flex-col shrink-0 mx-auto -mt-5">
                                      <div className="flex gap-1">
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                        <div className="flex flex-col w-1/5">
                                          <img
                                            loading="lazy"
                                            srcSet="https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F661e1fa212c74d1c94d19e320025bbf6%2F876decf19aa4453cac3b9268bdb2e695"
                                            className="box-border object-cover overflow-hidden shrink-0 mx-auto mt-5 w-full aspect-[1.05] max-w-[32px] min-h-[20px] min-w-[20px]"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
