import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import AuthComponent from "./components/AuthComponent";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, chatslot }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <AuthComponent>
        <div>{chatslot}</div>
        <div>{children}</div>
        
      </AuthComponent>
      </body>
    </html>
  );
}
